# Generated by Django 2.0.5 on 2018-05-16 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boss', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Boss',
        ),
        migrations.AlterModelTable(
            name='boss',
            table='Boss',
        ),
    ]
