# Generated by Django 2.0.5 on 2018-06-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180624_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='member_price',
            field=models.DecimalField(blank=True, decimal_places=28, max_digits=40, null=True, verbose_name='会员价'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=28, max_digits=40, verbose_name='零售价'),
        ),
    ]
