# Generated by Django 2.0.5 on 2018-06-08 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180608_0146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discounted_price',
        ),
        migrations.AddField(
            model_name='product',
            name='member_price',
            field=models.DecimalField(decimal_places=6, default=200, max_digits=10, verbose_name='会员价'),
            preserve_default=False,
        ),
    ]
