# Generated by Django 2.0.5 on 2018-06-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180608_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
    ]
