# Generated by Django 2.0.5 on 2018-05-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, verbose_name='乘客姓名')),
                ('age', models.IntegerField(verbose_name='乘客年龄')),
            ],
        ),
    ]
