# Generated by Django 2.0.5 on 2018-05-16 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='client',
            table='Client',
        ),
    ]
